### ISSUE TITLE
BUG: rufo generates invalid ruby code

### ISSUE THREAD

**Issue by martinos** [ruby-formatter/rufo#100]
I am using ruby 2.1.3 and rufo 0.3.1. when I try to format the following:

```ruby
class FormatError
  scope :my_scope, lambda { |tata|
    where([%{coco} , tata])
    .order("")
  }
end
```
I get this broken ruby code
```ruby
class FormatError
  scope :my_scope, lambda { |tata|
    where([%{coco}, tata])
rder("")
  }
end

```

**Comment by gingermusketeer** [comment]
@martinos Ruby 2.1 is no longer supported by the [ruby team as of March 2017](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/).

Also rufo does not support versions of ruby below `2.2.4`. However `>= 2.3.5`  or `>= 2.4.2` are recommended due to bugs in the ruby parser for versions below those.

Perhaps we should do a better job of calling out the versions of ruby that are supported.

**Comment by gingermusketeer** [comment]
I tried to reproduce this issue on `2.4.2` and was unable to do so. I suspect that it is the version of ruby that is the issue here.

**Comment by martinos** [comment]
I agree that putting to much effort on making Rufo work on ruby 2.1 is not really the best thing to do. However I wanted to report the issue just in case that someone hits the same problem.

**Comment by gingermusketeer** [comment]
@martinos That is a great point. Would You mind having a look at #101. I think that would be the best approach so that we don't introduce errors to code like happened to you.
