### ISSUE TITLE
Double quotes ?

### ISSUE THREAD

**Issue by waghanza** [ruby-formatter/rufo#103]
Hi,

New to `rufo`, I can see that string surrounded by simple quotes are turned into double quotes surrounded ones ?

As I remembered, simple quotes string are less resource consuming if there is no interpolation in it, right ?

Regards,

**Comment by glebm** [comment]
Also less mental overhead - if I see a single-quoted string I know it won't have any interpolations

**Comment by waghanza** [comment]
no performance diffs ?

**Comment by bessey** [comment]
I don't think this is clear cut, personally I use always double quotes
because:

1. Performance is completely irrelevant. There isn't a difference in
performance between "a string" and 'a string', but even if there were, how
a string is instantiated is a minuscule proportion of any programs runtime
and is not that right thing to be optimising. A better concern is avoiding
repeated string allocation via the frozen string literal magic comment.
2. I think it is self evident when a string has interpolation in it without
having differing syntax
3. I don't want to have to change the syntax of a string back and forth as
I add and remove interpolation syntax.

Per the rubocop ruby-style-guide
<https://github.com/rubocop-hq/ruby-style-guide#strings> I am an option b
person

**Comment by wuarmin** [comment]
Check this out!! After all it's a decision about performance: https://anti-pattern.com/always-use-double-quoted-strings-in-ruby
