### ISSUE TITLE
Heredoc issue: rufo places comma in wrong place

### ISSUE THREAD

**Issue by taw** [ruby-formatter/rufo#196]
With this code:

```ruby
describe "CLI Frontend" do
  it "error_reporting" do
    assert_cli(
      output: <<-EOF,
        Dragonlord Kolaghan
        Kolaghan Aspirant
        EOF
      error: <<-EOF
        Trying spelling "kolaghan" in addition to "kolagan"
        EOF
    )
  end
end
```

Comma is placed in wrong place:

```ruby
describe "CLI Frontend" do
  it "error_reporting" do
    assert_cli(
      output: <<-EOF,
        Dragonlord Kolaghan
        Kolaghan Aspirant
        EOF
      error: <<-EOF
        Trying spelling "kolaghan" in addition to "kolagan"
        EOF,
    )
  end
end```

**Comment by Jay-Schneider** [comment]
I have a very similar problem to report, where rufo breaks heredocs by adding a comma to the terminating name. When a method `foo` accepts say keyword arguments `s` and `t`, the code
```
foo(
  s: "string",
  t: <<~HEREDOC
    heredoc
  HEREDOC
)
```
gets transformed to
```
foo(
  s: "string",
  t: <<~HEREDOC
    heredoc
  HEREDOC,
)
```
by rufo which is invalid because the heredoc never ends until EOF.

I can workaround this by writing something like
```
foo(s: "string",
  t: <<~HEREDOC
    heredoc
  HEREDOC
)
```
which will not be broken by rufo because it just gets changed to
```
foo(s: "string",
    t: <<~HEREDOC
      heredoc
    HEREDOC
)
```

However this solution does not work in the case of multiple heredocs but only when I am able to place it last because rufo does not add a comma to the last argument (which rather looks like unintended behaviour as well).

Maybe someone can use this information to work on a fix? This kind of prevents me from using rufo in some projects where heredocs are widely used.

**Comment by Jay-Schneider** [comment]
Ah, I did a little reading and found a better solution to my own problem.
@taw one way to prevent rufo to add this comma would be postponing your heredoc definition and only declare it in the function call.
What I mean is writing
```
describe "CLI Frontend" do
  it "error_reporting" do
    assert_cli(output: <<-OUTPUT, error: <<-ERROR)
        Dragonlord Kolaghan
        Kolaghan Aspirant
        OUTPUT
        Trying spelling "kolaghan" in addition to "kolagan"
        ERROR
  end
end
```
(with other indentation, if you wish – or even with squiggly-heredoc).
This still requires to write the arguments in one line as far as I can see though. But I think this would solve your problem as long as rufo behaves this way.
