### ISSUE TITLE
Issues with quote_style

### ISSUE THREAD

**Issue by wimo7083** [ruby-formatter/rufo#99]
# Bug Report
## What is the current behavior?
When I try and use vscode with rufo, or use rufo from the command line I cannot get single quotes to get converted to double quotes.

## What is the expected behavior?
Rufo will respect the .rufo config and turn double quotes into single quotes. 

## What steps did you take to get this behavior?
I'm pretty new to ruby and rufo in general. I have a very simplistic `.rufo` file:

```
quote_style :single
trailing_commas true
```
When I use this and use vscode-rufo I get no error, but the single are not changed. I know it's recognizing the config because when I change to an invalid option:

```
quote_style single
```

I get an error. The trailing comma configuration works fine. I've looked into the recent pull request that intended on fixing this, but I don't know the correct way to make it work. This is most likely an error on my end. But I can't find what to do to fix it.

### Operating System
Windows 10

Screenshots:
![image](https://user-images.githubusercontent.com/10781353/39097862-4af1a538-461f-11e8-80cf-a5bab3716140.png)

PS: I'm using our issue template: https://github.com/OperationCode/operationcode_backend/blob/master/.github/ISSUE_TEMPLATE.md would recommend one for your amazing project. It really helps filter out low effort submissions.

**Comment by gurgeous** [comment]
Hi wimo, thanks for the great bug report! Can you check which version of rufo you are using? Rufo 0.3.0 had a bad bug (#95) which was quickly fixed in 0.3.1. The behavior you are reporting matches that bug.

The easiest way to check is to open a terminal in vscode (View > Integrated Terminal) and run `rufo -v` or `gem list rufo`.  If you are still on 0.3.0, try upgrading to 0.3.1. There are a few different ways to upgrade depending on how you installed the gem originally. Check back in with us if you get stuck.

Welcome to Ruby, and good luck!

**Comment by wimo7083** [comment]
That worked thanks for the help.

**Comment by TorvaldsDB** [comment]
Hey guys. How to find the file `.rufo`? Or where to se the file?

**Comment by gingermusketeer** [comment]
@TorvaldsDB can you create a new issue with more details of the problem you are having with the .rufo file rather than commenting on this resolved issue
